package logtags

const (
	ApisPreActionError                  = "ApisPreActionError"
	SyncingCitiesError                  = "SyncingCitiesError"
	CannotGetAccessTokenError           = "CannotGetAccessTokenError"
	BalanceLimitReached                 = "BalanceLimitReached"
	CannotCreateHttpBody                = "CannotCreateHttpBody"
	CannotCreateRequestObject           = "CannotCreateRequestObject"
	SmsProviderError                    = "SmsProviderError"
	CannotCreateOrUpdateHotel           = "CannotCreateOrUpdateHotel"
	CannotRemoveHotelFAQ                = "CannotRemoveHotelFAQ"
	UpdatingHotelsError                 = "UpdatingHotelsError"
	UpdatingHotelsCompleted             = "UpdatingHotelsCompleted"
	SyncHotelsError                     = "SyncHotelsError"
	SyncingHotelsCompleted              = "SyncingHotelsCompleted"
	GettingHotelDetailError             = "GettingHotelDetailError"
	GettingHotelTypeError               = "GettingHotelTypeError"
	CannotCompleteOrderPayment          = "CannotCompleteOrderPayment"
	NewRefundRequest                    = "NewRefundRequest"
	UpdatingRateAndReviewError          = "UpdatingRateAndReviewError"
	GettingListOfRefundableOrdersError  = "GettingListOfRefundableOrdersError"
	CannotCreateRefundEventError        = "CannotCreateRefundEventError"
	CannotPublishRefundEventError       = "CannotPublishRefundEventError"
	RefundRequestCompleted              = "RefundRequestCompleted"
	CastRateReviewEventObjectError      = "CastRateReviewEventObjectError"
	CannotSubscribeToRateReviewQueue    = "CannotSubscribeToRateReviewQueue"
	NewHotelIdDetected                  = "NewHotelIdDetected"
	InitializingCacheStoresError        = "InitializingCacheStoresError"
	UpdatingHotelsJobError              = "UpdatingHotelsJobError"
	UpdatingHotelsJobCompleted          = "UpdatingHotelsJobCompleted"
	GettingListOfHotelsError            = "GettingListOfHotelsError"
	FeedElasticError                    = "FeedElasticError"
	SearchCompleted                     = "SearchCompleted"
	CallingAliasError                   = "CallingAliasError"
	CreatingSeederError                 = "CreatingSeederError"
	RabbitUnknownError                  = "RabbitUnknownError"
	RabbitConnectionError               = "RabbitConnectionError"
	HotelAvailableCompleted             = "HotelAvailableCompleted"
	OrderFinalizedCompleted             = "OrderFinalizedCompleted"
	ConfirmOrderCompleted               = "ConfirmOrderCompleted"
	PayByAccountCompleted               = "PayByAccountCompleted"
	RunRouteError                       = "RunRouteError"
	CreateFeederError                   = "CreateFeederError"
	DbHealthCheckFailed                 = "DbHealthCheckFailed"
	ServiceHealthCheckFailed            = "ServiceHealthCheckFailed"
	SyncingHotelsJobCompleted           = "SyncingHotelsJobCompleted"
	IrrelevantResponseFromProviderError = "IrrelevantResponseFromProviderError"
	InvalidJsonResponseError            = "InvalidJsonResponseError"
	GettingCancellationPolicyError      = "GettingCancellationPolicyError"
	DatesNotMatchError                  = "DatesNotMatchError"

	GetAccessTokenRequest        = "GetAccessTokenRequest"
	SearchHotelsRequest          = "SearchHotelsRequest"
	GetHotelOptionInfoRequest    = "GetHotelOptionInfoRequest"
	HotelAvailableRequest        = "HotelAvailableRequest"
	ConfirmOrderRequest          = "ConfirmOrderRequest"
	PayByAccountRequest          = "PayByAccountRequest"
	GetOrderEnquiryRequest       = "GetOrderEnquiryRequest"
	GetOrdersRefundStatusRequest = "GetOrdersRefundStatusRequest"
	RefundOrderRequest           = "RefundOrderRequest"
	GettingHotelsListError       = "GettingHotelsListError"

	GinRequestFailed = "GinRequestFailed"
)
